---
version: "3.4"
services:
  nautobot:
    build:
      target: final-dev
    image: "local/nautobot-final-dev:local-py${PYTHON_VER}"
  worker:
    image: "local/nautobot-final-dev:local-py${PYTHON_VER}"
